### ISSUE TITLE
Bug in Package Application task: Unexpected token {

### ISSUE THREAD

**Issue by bderfer68** [OctopusDeploy/OctoTFS#100]
This release and its subsequent updates contain a significant bug in the Octopus "Package Application" task. When that task was auto-updated to version 3.0.162 from version 2.x, the Package Application task now breaks with the following error:

[error]Unhandled: Unexpected token {

There are no clues in the error about where the error occurs. We hit the error regardless of what is being built or what build definition calls it. It seems like there is some poorly structured json in one of the many json files. I've looked at probably two dozen of them and run them through a json validator, and so far have not found a culprit.

**Comment by shaunmarx** [comment]
Hi @bderfer68 sorry to hear that you are running into issues and sorry for the slow response.

That error message is quite bizarre and I don't really know what to make of it. Are you currently using VSTS or TFS? If the latter what version are you using? Are both the v2 and v3 `Package Application` tasks failing for you and are there any other V3 Octopus tasks which are currently working? If you weren't aware, you can adjust the task version using the dropdown at the top of the task when editing the build definition. This should be an explicit opt-in for existing tasks, while new tasks will default to the new major version.
![image](https://user-images.githubusercontent.com/6700195/44335336-798c2c00-a4b7-11e8-9b51-66f2b66b8722.png)

Could you provide us with a full build log containing the error as well as a list of the agent capabilities, please? 

If you aren't comfortable sharing information here, then you can use one of our [support channels](https://octopus.com/support) instead and simply link this issue and we can pick things up from there.

**Comment by stuartwells** [comment]
Was this resolved? I am getting the same issue.

Brand new - so not an upgrade - but first Package Application Task in Build failed with this error. Not sure what { it is on about.

**Comment by shaunmarx** [comment]
Hi @stuartwells unfortunately not, we needed some additional information in order to reproduce, which we have been unable to do thus far. Are you getting this error across all of the Octopus tasks? Could you share some more information regarding your current setup such as whether you are using TFS / Azure Devops, version if the former, as well as capabilities for the build agent as well as the operating system?

The error does seem to happen before anything gets executed which seems to suggest the extension is somehow corrupt. If you are using TFS or your own build agent with Azure Devops, could we maybe get one of the failing octopus tasks from your build agent sent through to https://help.octopus.com/, please?  These would usually be located in your build agent root folder in a path like the following: `_work/_tasks/OctopusPack_ba79430a-bd26-4fc0-b827-6e442de623e4/3.0.xxxx`

**Comment by stuartwells** [comment]
I raised this directly with Octopus support - for completeness I stumbled on the solution...turns out that whilst the TFS version for editing build definitions was indeed 2017 Update 3...we had several Build Agent Queues and the queue this build definition was running on was only 2015...I change the queue to use to another one that was 2017 and it worked.

**Comment by shaunmarx** [comment]
Thanks for getting back to us Stuart. That definitely does explain a lot :). I was under the impression that Azure Devops / TFS would prevent the tasks from running on build agents where it would fail like that. I will leave this issue open until we can determine whether there is anything we can do to prevent this from happening such as updating the task manifests.

Thanks again for the information, this one had us scratching our heads for quite a while 👍
