### ISSUE TITLE
Support wildcards in OctoInstaller task

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/OctoTFS#229]
Versions can be given in the following formats, examples:

- `8.*` => Install latest in major version.
- `7.3.*` => Install latest in major and minor version.
- `8.0.1` => Install exact version.
- `*` => Install whatever is latest.

**Comment by jbristowe** [comment]
Is it worth considering SemVer ranges?

**Comment by johnsimons** [comment]
> Is it worth considering SemVer ranges?

I assume customer will tell us eventually ;)

**Comment by twurm** [comment]
@johnsimons any idea when this will be ready?

**Comment by johnsimons** [comment]
@twurm hopefully I get it merged today

**Comment by johnsimons** [comment]
@twurm I'm curious, which one are you after?

**Comment by twurm** [comment]
@johnsimons I think they all make sense honestly.  We will be using the * (if available), mainly because we are using Octopus in the cloud so that seems to make the most sense.  If we were using on premise, the 8.* would make the most sense, if we run into a regression in the CLI we will be using the full 8.1.1.

**Comment by jbristowe** [comment]
Thanks for the feedback, @twurm. Our implementation will enable you to run on latest (AKA, `*`) with the understanding that this includes updates to major versions, which includes breaking changes. I don't anticipate a lot of major versions in the future. However, if a breaking change is introduced then this may require you to update your workflows.
