### ISSUE TITLE
Missing usage information on OctoCli task in VisualStudio Marketplace

### ISSUE THREAD

**Issue by dotnokato** [OctopusDeploy/OctoTFS#275]
I love your tasks for Azure DevOps!
They are super useful and using them allows my yaml pipelines to look neat and easy to understand.

However, it would be great if you could improve the usage instructions available on [Octopus Deploy Integration page in Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks).
It does not list options for OctoCli task, I had to look into the source code to figure out the available inputs.

Same with task names and input parameter names for yaml pipelines - took me quite some time to figure out why my release notes were not being correctly created by `OctopusCreateRelease`. Turns out the input is named "CustomReleaseNotes" and not "ReleaseNotes" as label suggests (`"label": "Release Notes"`).

Or maybe there is a reference for yaml pipelines and I just cannot find it 😬

**Comment by slewis74** [comment]
Hi @dotnokato, thanks for the feedback. We agree, some of the field names are a bit confusing, and the documentation at the moment is lacking. Naming is related to the history of the steps in the plug, it was created long before the YAML pipelines existed and the name were only internal to the plugin. Some names were picked based on internal names for things, or how certain parts of the API thought about things, because they weren't visible to users anyway. Now they are.

We currently working on a v6 update for all of the steps, to take advantage of some new features in the later versions of Octopus (per the recent changes we made to our GitHub Actions). As part of this we're going to be updating the documentation in the marketplace to include details of the exact YAML inputs and outputs that each step supports. Hopefully that will make this easier in the future, so please keep an eye out for that release.

**Comment by benPearce1** [comment]
This updated documentation will be available when v6 ships in the next few days.
