### ISSUE TITLE
Filter Changeset Comments 

### ISSUE THREAD

**Issue by thomasf7** [OctopusDeploy/OctoTFS#31]
In one VSTS collection we have multiple solutions, each with multiple branches. I have configured a CI build definition that is triggered on one of these branches and using a combination of octopack and the "Create Octopus Release" build step to automate the deployment process.

This is all working excellently and being able to include Changeset comments is awesome so we have visibility into what is included in the release. However, I have now noticed that the option to include all changeset comments does so for the whole collection (since last build) - not just the branch this release is triggered from.

Is it possible to have the ability to filter the release notes? Either as a configurable value in the build step, based on the repository mapping or some other configuration in the build definition?

**Comment by Damovisa** [comment]
Hi @thomasf7,

Thanks for the feedback and I understand the difficulty.

This step simply relies on whatever VSTS decides are related changesets for that build. If you have a look at the build page when it finishes, there are a series of links for related changesets. We don't calculate those - they come from VSTS.

It would be entirely possible to apply a filter, but having a single solution that works for everyone is likely to get messy. I'd really like to keep this step fairly simple.

You could uncheck the release notes checkboxes for this step, and update the Release object in Octopus using your own subsequent step. I suspect a lot of the code in this step could be reused for this purpose. That would give you ultimate control over what appears.

You could also fork this repository and change the logic to behave better for your situation. Unfortunately you would have to upload the custom step manually rather than use the extension.

Alternatively if you can think of a nice way of solving this in a generic way, we do accept pull requests!

Thanks,
Damian Brady

**Comment by philip-reed** [comment]
@Damovisa 

Could the repository mapping in VSTS be used to filter the comments?
I've been looking through the API for VSTS and I have a couple of ideas how this could be done, but I struggle with creating a test environment to experiment.  Is there any material anywhere to help support people who want to try submitting a PR? I don't want to break my employers LIVE Octopus environment.

Thanks,
Phil

**Comment by Damovisa** [comment]
Hi Phil,

Filtering based on the mapping would probably work, yes. To be honest I'm a little surprised every change in the collection is linked to that build. I would have thought it would be restricted to just the Project at least?

The story for testing plugin changes is a bit tricky, but we have a [walkthrough you can follow](http://docs.octopusdeploy.com/pages/viewpage.action?pageId=3049169) for installing your own version.

To make changes and test, you'll probably have to install at least a new Octopus project and test with a separate VSTS project as well. If you isolate these, it shouldn't be too difficult - it's just a little time consuming.

Good luck!
Damian

**Comment by rachkoud** [comment]
Hello,

We had a similar problem, our goal was to have a full traceability of our Octopus Releases, we would like to be able know what changeset/branch has produced the release. _Include Changeset Comments_ produces unpredictable results, sometimes you have others changesets or no changesets at all. There is a simple option to get the changeset id and branch used by adding a custom notes and use the [predefined variables](https://www.visualstudio.com/en-us/docs/build/define/variables#predefined-variables) like this  : 

![image](https://cloud.githubusercontent.com/assets/1620056/16613018/3c51b9c8-436a-11e6-88fb-d796ead702b9.png)

And then, you can view in the Octopus Release notes what was the changeset/branch that has been used : 

![image](https://cloud.githubusercontent.com/assets/1620056/16613152/080f2686-436b-11e6-9611-3c006c116b0e.png)

Hope it helps!
Rach
