### ISSUE TITLE
Use assembly version

### ISSUE THREAD

**Issue by kria** [OctopusDeploy/OctoTFS#53]
At the moment I'm using OctoPack together with a Create Release step. 
I'd like to replace OctoPack with the new Pack and Push tasks, but one thing I'm missing is using the assembly version in the package name like OctoPack does.

Is this something you plan on adding to the tasks?

**Comment by bzbetty** [comment]
Think i have a similar issue.  Create Release seems to grab the latest package version and not necessarily the one that was just uploaded.

**Comment by Damovisa** [comment]
Hi @kria,

Unfortunately there's not really a way to do this. The Pack task essentially just zips a folder. You can provide a version for the package, but the contents of that folder may come from a few projects or possibly not from a compilation at all - so there's no way to determine a single version.

You might look at using the build number rather than the one in AssemblyInfo, or if you're really keen, you could populate a variable from another task that reads from your compiled binaries (or even the AssemblyInfo file directly?)

Sorry if this wasn't the answer you were after!

Damian
