### ISSUE TITLE
Package application task includes everything

### ISSUE THREAD

**Issue by bzbetty** [OctopusDeploy/OctoTFS#57]
When using the package application task it includes everything in the directory, would be nice if it was more like octopack and included just what was needed (maybe allow Source Path to be a csproj file instead of a folder?)

**Comment by Damovisa** [comment]
Hi @bzbetty,

Yeah, I totally understand the request. Unfortunately it's not something we're likely to do. Octopack is a bit special because it ties into the MSBuild process so can see what type of project it is and what files would be required in a package.

The Package step on the other hand just uses `octo.exe`, which is a quick way to package up a folder.

Your best bet would be to use OctoPack if you can, or `NuGet.exe` directly if you have a nuspec file. Alternatively, you may be able to add MSBuild arguments that publish to the local filesystem so you can pack that folder.
