### ISSUE TITLE
Commit is not included in Release Notes

### ISSUE THREAD

**Issue by olsh** [OctopusDeploy/OctoTFS#95]
**Configuration:** 
We use `Create Octopus Release` task version 2.0.107 on TFS 2018 Update 2 and we have a task with one related commit. The commit is displayed as a related item on the Task page.
When we create a release using `Create Octopus Release` and have both checkboxes checked `Include Changeset Comments` and `Include Work Items`.

**Expected behavior:**
_Both the commit and the task are included_ in the Release Notes.

**Actual behavior:**
_Only the task is included_ in Release Notes.

Please note, that the described issue is not stable and appears from time to time, probably when there are too many commits in a release and some of them are truncated.

**Comment by Dalmirog** [comment]
Hi @olsh . I'm having troubles reproducing this one. With how many `tasks` and `commits` were you able to trigger this behavior?

Any chance you can share me the full TFS build log so I can check the `Octo.exe` commands that are being executed on the background? Please email it to `support@octopus.com` and we can continue our conversation there.

**Comment by olsh** [comment]
Hi @Dalmirog! 
Are there any updates on this? Are you able to reproduce the issue?
I've emailed support@octopus.com but got no response.

**Comment by Dalmirog** [comment]
HI @olsh , sorry for the delay here! I've replied back to you from our support account as I need to ask you for logs that you wouldn't want to share on this public channel.

Let's continue our conversation over there. I'll add a new comment on this thread once we reach to a conclusion for you issue in order to help anyone else that runs into this.

**Comment by Dalmirog** [comment]
This issue seems to be related to https://stackoverflow.com/questions/48674968/how-do-i-get-more-than-50-associated-work-items-for-a-vsts-build  and https://developercommunity.visualstudio.com/content/problem/38322/tfs-2017-update1-associated-work-items-for-a-build.html

We might have to opt in for the solution described in the SO thread where they got all related changesets and then all work items for each changeset.

Reports:
- (private) https://secure.helpscout.net/conversation/608977769/28496?folderId=571746

**Comment by olsh** [comment]
Hi @Dalmirog,

I've just upgraded the extension. I will let you know if the issue exists.

**Comment by olsh** [comment]
Hey @Dalmirog 

Sorry for the super late response, sadly, I can help with the issue since we don't use TFS anymore.
